name: amongdemons.com
main: alurosu.minecraft.survival.plugin
version: 3.0
depend: [Vault]
loadbefore: [GriefPrevention]
api-version: 1.13
author: alurosu
website: alurosu.com
commands:
  login:
    description: login
    usage: /login
    aliases: [l]
  kits:
    description: kits
    usage: /kits
    aliases: [kit, shop]
  souls:
    description: souls
    usage: /souls
    aliases: [s]
  map:
    description: map
    usage: /map
  help:
    description: help
    usage: /help
    aliases: [info]