name: amongdemons.com
main: alurosu.minecraft.survival.plugin
version: 3.2
depend: [Vault, dynmap]
loadbefore: [GriefPrevention, AdvancedTeleport, PowerRanks]
api-version: 1.13
author: alurosu
website: alurosu.com
commands:
  login:
    description: login
    usage: /login
    aliases: [l]
  register:
    description: register
    usage: /register
    aliases: [reg]
  kits:
    description: kits
    usage: /kits
    aliases: [kit, shop]
  claimkits:
    description: claimkits
    usage: /claimkits
    aliases: [claimkit]
  souls:
    description: souls
    usage: /souls
    aliases: [s]
  map:
    description: map
    usage: /map
  help:
    description: help
    usage: /help
    aliases: [info]
  addmarker:
    description: addmarker
    usage: /addmarker
  delmarker:
    description: delmarker
    usage: /delmarker
    aliases: [deletemarker, removemarker]
